apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "inker-back.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
  {{ $key | toString }}: {{ $val | b64enc }}
  {{- end}}