apiVersion: v1
kind: Service
metadata:
  name: {{ include "inker-back.fullname" . }}
  labels:
    app: {{ .Chart.Name }}-{{ .Values.image.tag }}
    {{- include "inker-back.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | quote | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containers.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "inker-back.selectorLabels" . | nindent 4 }}
